function [rnd, abs, rel] = GetErrors(K)
%GETERRORS returns rounded absolute error, absolute error, and relative
%error
%
%   [rnd, abs, rel] = GETERRORS(K) returns the errors of the true matmul
%   tensor minus the approximation generated by cylic matrices when
%   transformed into factor matrices where:
%       rnd -> ||True - round(Approx)||
%       abs -> ||True - Approx||
%       rel -> ||True - Approx||/||True||

    n = sqrt(size(K{1},1));
    
    T = MatMulTensor(n,n,n);
    U = cyc2fac(K);
    R = cyc2fac(cellfun(@(x) round(x), K, 'UniformOutput', false));
    
    rnd = norm(T - full(ktensor(R)));
    abs = norm(T - full(ktensor(U)));
    rel = abs/norm(T);
end